services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3 # Remplacez par la version souhaitée
    container_name: elasticsearch
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Désactiver la sécurité (facultatif en dev/test)
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # Allouer 1 Go de RAM à Elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200" # Port HTTP pour Elasticsearch
      - "9300:9300" # Port pour le cluster (si nécessaire)


  mts-discovery-service:
    container_name: mts-discovery-service
    build:
      ./discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: [ "CMD", "curl","-f" , "http://localhost:8761/actuator/health" ]
      interval: 15s


  mts-config-service:
    container_name: mts-config-service
    environment:
      - DISCOVERY_SERVICE_URL=http://mts-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://mts-config-service:9999
      - CONFIG_PROFILE:dev
    build:
      ./config-service
    ports:
      - "9999:9999"
    expose:
      - "9999"
    healthcheck:
      test: [ "CMD", "curl","-f" , "http://localhost:9999/actuator/health" ]
      interval: 10s

    depends_on:
      mts-discovery-service:
        condition: service_healthy


  mts-gateway-service:
    container_name: mts-gateway-service
    environment:
      - DISCOVERY_SERVICE_URL=http://mts-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://mts-config-service:9999
      - CORS_ALLOWED_ORIGIN=*
    build:
      ./gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"

    depends_on:
      mts-config-service:
        condition: service_healthy

  mts-images-service:
    container_name: mts-images-service
    environment:
      - DISCOVERY_SERVICE_URL=http://mts-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://mts-config-service:9999
      - SPRING_PROFILES_ACTIVE=dev
    build:
      ./images-service
    ports:
      - "8083:8083"
    expose:
      - "8083"
    healthcheck:
      test: [ "CMD", "curl","-f" , "http://localhost:8083/actuator/health" ]
      interval: 10s
    depends_on:
      mysql:
        condition: service_started
      mts-config-service:
        condition: service_healthy


  mts-location-service:
    container_name: mts-location-service
    environment:
      - DISCOVERY_SERVICE_URL=http://mts-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://mts-config-service:9999
      - SPRING_PROFILES_ACTIVE=dev
    build:
      ./location-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    healthcheck:
      test: [ "CMD", "curl","-f" , "http://localhost:8081/actuator/health" ]
      interval: 10s
    depends_on:
      mysql:
        condition: service_started
      mts-config-service:
        condition: service_healthy


#  mts-mail-service:
#    container_name: mts-mail-service
#    environment:
#      - DISCOVERY_SERVICE_URL=http://mts-discovery-service:8761/eureka
#      - CONFIG_SERVICE_URL=http://mts-config-service:9999
#    build:
#      ./mail-service
#    ports:
#      - "8085:8085"
#    expose:
#      - "8085"
#    depends_on:
#      mts-config-service:
#        condition: service_healthy


#  mts-users-service:
#    container_name: mts-users-service
#    environment:
#      - DISCOVERY_SERVICE_URL=http://mts-discovery-service:8761/eureka
#      - CONFIG_SERVICE_URL=http://mts-config-service:9999
#    build:
#      ./users-service
#    ports:
#      - "8082:8082"
#    expose:
#      - "8082"
#    depends_on:
#      mts-images-service:
#        condition: service_started

  mts-announces-service:
    container_name: mts-announces-service
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - DISCOVERY_SERVICE_URL=http://mts-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://mts-config-service:9999
      - SPRING_PROFILES_ACTIVE=dev
    build:
      ./announces-service
    ports:
      - "8086:8086"
    expose:
      - "8086"
    depends_on:
      mysql:
        condition: service_started
      elasticsearch:
        condition: service_started
      mts-images-service:
        condition: service_started

#  nginx:
#    container_name: nginx
#    build:
#      ./nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      mts-gateway-service:
#        condition: service_started


  front-end:
    container_name: front-end
    depends_on:
      mts-gateway-service:
        condition: service_started
    build:
      ./frontend
    ports:
      - '80:80'
    expose:
      - '80'

  mysql:
    build:
      ./database
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adryvo
      MYSQL_USER: adryvo
      MYSQL_PASSWORD: adryvo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  es_data:
  mysql_data: {}