spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://193.203.191.159"
            allowed-headers: '*'
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT