spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "${CORS_ALLOWED_ORIGIN:http://localhost:2400}"
            allowed-headers: '*'
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT