# Utilisation de l'image officielle MySQL
FROM mysql:8.0

# Copie des fichiers initiaux (optionnel)
# Vous pouvez ajouter des scripts SQL ou des configurations personnalisées
#COPY ./init-db /docker-entrypoint-initdb.d/

# Exposition du port MySQL
EXPOSE 3306